spring.application.name=CKNhom11QLHOTEL

spring.datasource.url=jdbc:mysql://localhost:3306/hotelnhom11
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Tự động tạo/cập nhật bảng (update, create, create-drop, none)
spring.jpa.hibernate.ddl-auto=update
# Hiển thị SQL ra console (tùy chọn)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dv8kytctn}
cloudinary.api-key=${CLOUDINARY_API_KEY:535262311929529}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:84mcx7kKseOP_IrewyVGwyRngsk}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

