@startuml
package "view (templates)" as view { }
package "controller" as controller { }
package "service" as service { }
package "repository" as repository { }
package "model" as model { }
package "stream" as stream { }
package "config" as config { }
package "util" as util { }
package "init" as init { }

view --> controller
controller --> service
controller --> model
service --> repository
service --> model
service --> util
service --> stream
repository --> model
stream --> model
controller --> util
init --> service
@enduml